"""Infrastructure · Cyanite REST wrapper. The only place in the project that touches the network.

The orchestration layer only calls functions here; tests can monkeypatch this module to run offline.
REST shapes come from notebooks/cyanite_model_outputs.ipynb and the official PDFs under guides/.

Four official endpoints ↔ functions in this module:
  #1 GET  /v1/library-tracks/{id}/models            -> model_tags()      (tagging)
  #2 POST /v1/private-alpha/library-tracks/search   -> search_by_prompt() (prompt search)
  #3 POST /v1/private-alpha/library-tracks/{id}/similar -> find_similar()  (single seed)
  #4 POST /v1/private-alpha/library-tracks/similar  -> find_similar_multi() (<=10 seeds)
"""
from __future__ import annotations
import csv
import hashlib
import json
import pathlib

import requests
from requests.adapters import HTTPAdapter
from urllib3.util import Retry

import config

_DATA_DIR = pathlib.Path(__file__).resolve().parents[1] / "data"
_DATA = _DATA_DIR / "tracks.csv"

# Data-pack CSV: real display info (including artist) for ~10k "taste seed" tracks, loaded once at startup.
# This is only a cache/seed set: non-seed tracks returned by search/similar are not here, so title/artist
# come from Jamendo, and track_id is taken directly from `{jamendoId}.mp3` in the Cyanite response
# (see normalize / display).
_JAM_TO_CYAN: dict[str, str] = {}
_DISPLAY: dict[str, dict] = {}
with _DATA.open() as f:
    for row in csv.DictReader(f):
        _JAM_TO_CYAN[row["track_id"]] = row["cyanite_id"]
        _DISPLAY[row["cyanite_id"]] = {
            "track_id": row["track_id"],
            "cyanite_id": row["cyanite_id"],
            "title": row.get("name", ""),
            "artist": row.get("artist_name", ""),
        }
_CYAN_TO_JAM = {c: j for j, c in _JAM_TO_CYAN.items()}

# Shared rate-limit backoff: Cyanite has a shared rate limit, and explain fan-out multiplies requests.
# Retry 429/5xx automatically, honor server Retry-After, and raise only after exhausting retries.
# Covers all four endpoints.
_session = requests.Session()
_session.headers.update({"x-api-key": config.CYANITE_API_KEY})
_retry = Retry(total=4, backoff_factor=1, status_forcelist=(429, 500, 502, 503, 504),
               allowed_methods=frozenset({"GET", "POST"}), respect_retry_after_header=True)
_session.mount("https://", HTTPAdapter(max_retries=_retry))

# Jamendo metadata lookup: batched id[] queries occasionally timeout/5xx; read=2 retries read timeouts too,
# so the whole batch does not lose names.
_jam_session = requests.Session()
_jam_retry = Retry(total=3, read=2, connect=2, backoff_factor=0.5,
                   status_forcelist=(429, 500, 502, 503, 504), allowed_methods=frozenset({"GET"}))
_jam_session.mount("https://", HTTPAdapter(max_retries=_jam_retry))


# --- id / display ---
def to_cyanite(track_id: str) -> str:
    return _JAM_TO_CYAN[str(track_id)]


def to_jamendo(cyanite_id: str) -> str:
    """Data-pack seed tracks: cyanite_id -> jamendo track_id. Non-seed track_ids come directly from Cyanite responses."""
    return _CYAN_TO_JAM[cyanite_id]


def display(cyanite_id: str, track_id: str = "") -> dict:
    if cyanite_id in _DISPLAY:          # Data-pack seed track: has real title + artist.
        return _DISPLAY[cyanite_id]
    # Other catalog tracks: callers pass track_id directly from the Cyanite response ({jamendoId}.mp3).
    # Cyanite's library has no title/artist, so leave them empty and let enrich_meta fill from Jamendo.
    return {"track_id": track_id, "cyanite_id": cyanite_id, "title": "", "artist": ""}


def normalize(resp: dict) -> list[dict]:
    """Cyanite {items:[{track,score}]} -> [{cyanite_id, score, track_id}]。
    track_id comes directly from response track.title (Cyanite upload filename = {jamendoId}.mp3), independent of mapper."""
    out = []
    for it in resp.get("items", []):
        track = it.get("track", it)
        out.append({"cyanite_id": track.get("id"), "score": it.get("score"),
                    "track_id": str(track.get("title") or "").removesuffix(".mp3")})
    return out


# --- retrieval ---
def search_by_prompt(query: str, limit: int = config.SEARCH_LIMIT,
                     metadata_filter: dict | None = None) -> list[dict]:
    """freeTextSearch: natural language -> candidate tracks. metadata_filter is the hard filter generated by the intent agent."""
    body = {"query": query}
    if metadata_filter:
        body["metadataFilter"] = metadata_filter
    r = _session.post(f"{config.CYANITE_BASE_URL}/private-alpha/library-tracks/search",
                      params={"limit": limit}, json=body, timeout=60)
    r.raise_for_status()
    return normalize(r.json())


def _jamendo_one(track_id: str) -> dict | None:
    """Serially fetch one Jamendo track and return {title, artist}; return None on miss/failure."""
    if not config.JAMENDO_CLIENT_ID or not track_id:
        return None
    try:
        r = _jam_session.get(f"{config.JAMENDO_BASE_URL}/tracks",
                             params={"client_id": config.JAMENDO_CLIENT_ID,
                                     "id": track_id, "format": "json", "limit": 1},
                             timeout=15)
        r.raise_for_status()
        results = r.json().get("results", [])
        if not results:
            return None
        return {"title": results[0].get("name", ""), "artist": results[0].get("artist_name", "")}
    except Exception as e:
        print(f"[warn] Jamendo fetch failed for {track_id}: {e}")
        return None


def enrich_meta(cards: list[dict]) -> list[dict]:
    """Fill title/artist and drop cards that cannot get names.
    Keep CSV hits; serially query Jamendo for missing names and remove misses from results (do not render)."""
    out = []
    for c in cards:
        if c.get("title"):
            out.append(c); continue
        meta = _jamendo_one(c.get("track_id", ""))
        if meta and meta["title"]:
            c.update(meta)
            out.append(c)
        # Otherwise drop it: do not render tracks without real names.
    return out


def search_raw(query: str, limit: int = config.SEARCH_LIMIT) -> list[dict]:
    """freeTextSearch: use local metadata for CSV hits; fill title/artist for misses through the Jamendo API."""
    r = _session.post(f"{config.CYANITE_BASE_URL}/private-alpha/library-tracks/search",
                      params={"limit": limit}, json={"query": query}, timeout=60)
    r.raise_for_status()

    rows = []
    for it in r.json().get("items", []):
        track = it["track"]
        cid = track["id"]
        tid = str(track.get("title") or "").removesuffix(".mp3")
        meta = _DISPLAY.get(cid)
        rows.append({"cyanite_id": cid, "track_id": tid, "score": it["score"],
                     "title": meta["title"] if meta else "", "artist": meta["artist"] if meta else ""})

    return enrich_meta(rows)


def find_similar(cyanite_id: str, limit: int = config.SIMILAR_LIMIT) -> list[dict]:
    """#3 similarById (single seed): one track -> acoustically similar tracks."""
    r = _session.post(f"{config.CYANITE_BASE_URL}/private-alpha/library-tracks/{cyanite_id}/similar",
                      params={"limit": limit}, json={}, timeout=60)
    r.raise_for_status()
    return normalize(r.json())


def find_similar_multi(cyanite_ids: list[str], limit: int = config.SIMILAR_LIMIT) -> list[dict]:
    """#4 similar (multi-seed, <=10): a group of tracks -> combined acoustically similar tracks."""
    body = {"tracks": [{"id": cid} for cid in cyanite_ids[:10]]}
    r = _session.post(f"{config.CYANITE_BASE_URL}/private-alpha/library-tracks/similar",
                      params={"limit": limit}, json=body, timeout=60)
    r.raise_for_status()
    return normalize(r.json())


def model_tags(cyanite_id: str, models: list[str]) -> dict:
    """Fetch model tags for one track, for "Why this track?"."""
    params = [("model", m) for m in models]
    r = _session.get(f"{config.CYANITE_BASE_URL}/library-tracks/{cyanite_id}/models",
                     params=params, timeout=60)
    r.raise_for_status()
    return r.json()


# --- Feeling tags (used by memory's taste timeline, with disk cache) ---
_TAG_CACHE = pathlib.Path(__file__).resolve().parent / ".cache" / "models"
# version -> (output key, top-K). Only fetch the three feeling dimensions; do not download hard variables.
_FEEL_DIMS = {"MoodSimpleV2": ("moods", 4), "CharacterV2": ("character", 4),
              "MovementV2": ("movement", 3)}


def _flat_tags(mo: dict, thresh: float = 0.2, topk: int = 6) -> list[str]:
    """Flat tags: handle both summary `tags` and segmented `segments` (timeline max -> threshold -> top-K, to avoid context blow-up)."""
    if isinstance(mo.get("tags"), list):
        return mo["tags"]
    vals = (mo.get("segments") or {}).get("values") or {}
    if not vals:
        return []
    scored = sorted(((k, max(v or [0.0])) for k, v in vals.items()), key=lambda kv: -kv[1])
    return [k for k, m in scored if m >= thresh][:topk]


def feel_tags(cyanite_id: str, models: list[str]) -> dict[str, list[str]]:
    """Feeling tags for one track {moods/character/movement: [...]}, disk-cached by (id, models).
    ponytail: return cache hits immediately; misses call model_tags (429/backoff is handled by _session Retry)."""
    key = cyanite_id + "|" + ",".join(sorted(models))
    p = _TAG_CACHE / (hashlib.sha1(key.encode()).hexdigest() + ".json")
    if p.exists():
        return json.loads(p.read_text())
    out: dict[str, list[str]] = {}
    for mo in model_tags(cyanite_id, models).get("items", []):
        dim = _FEEL_DIMS.get(mo.get("version"))
        if dim:
            out[dim[0]] = _flat_tags(mo, topk=dim[1])
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(out))
    return out


def _selfcheck() -> None:
    """Offline self-check: seed tracks get real artist; non-seed track_id comes from caller (Cyanite response), title/artist empty."""
    pack_cid = next(iter(_DISPLAY))
    d = display(pack_cid)
    assert d["track_id"] and d["artist"], f"seed track should have track_id+artist: {d}"
    assert to_jamendo(pack_cid) == d["track_id"]
    # Non-seed track: track_id must be the value parsed by the caller from the API response; title/artist stay empty for Jamendo.
    n = display("libtr_doesnotexist", track_id="919998")
    assert n["track_id"] == "919998" and n["title"] == "", f"non-seed track should use API track_id and leave title empty: {n}"
    # normalize parses track_id directly from {jamendoId}.mp3, independent of any local mapping.
    assert normalize({"items": [{"score": 0.9, "track": {"id": "x", "title": "919998.mp3"}}]}) \
        == [{"cyanite_id": "x", "score": 0.9, "track_id": "919998"}]
    print(f"selfcheck: seed {pack_cid}->{d['artist']!r} / non-seed track_id comes from response")


if __name__ == "__main__":
    _selfcheck()
